/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABaseMap: typeof import('./src/components/A/BaseMap.vue')['default']
    ADotMapRegion: typeof import('./src/components/A/DotMap/Region.vue')['default']
    ALeafletCircleMarker: typeof import('./src/components/A/Leaflet/CircleMarker.vue')['default']
    ALeafletCluster: typeof import('./src/components/A/Leaflet/Cluster.vue')['default']
    ALeafletClusterAA: typeof import('./src/components/A/Leaflet/ClusterAA.vue')['default']
    ALeafletControl: typeof import('./src/components/A/Leaflet/Control.vue')['default']
    ALeafletControlAttribution: typeof import('./src/components/A/Leaflet/ControlAttribution.vue')['default']
    ALeafletControlZoom: typeof import('./src/components/A/Leaflet/ControlZoom.vue')['default']
    ALeafletMap: typeof import('./src/components/A/Leaflet/Map.vue')['default']
    ALeafletMarkerClusterGroup: typeof import('./src/components/A/Leaflet/MarkerClusterGroup.vue')['default']
    ALeafletTestDDD: typeof import('./src/components/A/Leaflet/TestDDD.vue')['default']
    ALeafletTileLayer: typeof import('./src/components/A/Leaflet/TileLayer.vue')['default']
    AOriginBaseMap: typeof import('./src/components/A/Origin/BaseMap.vue')['default']
    AOriginDotMap: typeof import('./src/components/A/Origin/DotMap/Index.vue')['default']
    BaseAreaMap: typeof import('./src/components/BaseAreaMap/Index.vue')['default']
    BaseMap: typeof import('./src/components/BaseMap.vue')['default']
    BaseMapBaseAreaMap: typeof import('./src/components/Base/Map/BaseAreaMap.vue')['default']
    CompanyDotMap: typeof import('./src/components/CompanyDotMap/Index.vue')['default']
    copy: typeof import('./src/components/Leaflet/ControlAttribution copy.vue')['default']
    DotMap: typeof import('./src/components/DotMap/Index.vue')['default']
    DotMapRegion: typeof import('./src/components/DotMap/Region.vue')['default']
    DotMapRegionDotMap: typeof import('./src/components/DotMap/RegionDotMap.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeafletCircleMarker: typeof import('./src/components/Leaflet/CircleMarker.vue')['default']
    LeafletCluster: typeof import('./src/components/Leaflet/Cluster.vue')['default']
    LeafletClusterAA: typeof import('./src/components/Leaflet/ClusterAA.vue')['default']
    LeafletControl: typeof import('./src/components/Leaflet/Control.vue')['default']
    LeafletControlAttribution: typeof import('./src/components/Leaflet/ControlAttribution.vue')['default']
    LeafletControlZoom: typeof import('./src/components/Leaflet/ControlZoom.vue')['default']
    LeafletMap: typeof import('./src/components/Leaflet/Map.vue')['default']
    LeafletMarkerClusterGroup: typeof import('./src/components/Leaflet/MarkerClusterGroup.vue')['default']
    LeafletTest: typeof import('./src/components/Leaflet/Test.vue')['default']
    LeafletTestDDD: typeof import('./src/components/Leaflet/TestDDD.vue')['default']
    LeafletTileLayer: typeof import('./src/components/Leaflet/TileLayer.vue')['default']
    OriginBaseMap: typeof import('./src/components/Origin/BaseMap.vue')['default']
    OriginDotMap: typeof import('./src/components/Origin/DotMap/Index.vue')['default']
    RegionCircleMap: typeof import('./src/components/RegionCircleMap.vue')['default']
    RegionDotMap: typeof import('./src/components/RegionDotMap/Index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
